name: CI
on:
  push:
    paths:
      - "lib/**"
      - "test/**"
      - "package.json"
      - "package-lock.json"
  pull_request:
    types: [opened]
    paths:
      - "lib/**"
      - "test/**"
      - "package.json"
      - "package-lock.json"
    branches:
      - "!*"
      - "develop"
      - "master"
    tags:
      - "!v*"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    strategy:
      matrix:
        elasticsearch-version: [7.15.0]

    steps:
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: ${{ matrix.elasticsearch-version }}

      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm ci
      - run: npm test

